import { Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Home, Languages, LockKeyhole, MessageCircle, Settings, Share2, Sparkles, UserRound, Users, Volume2, VolumeX } from "lucide-react";
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import en from "@/locales/en.json";
import ar from "@/locales/ar.json";
import { tracks, type Locale } from "@/lib/unidojo-data";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

type AppState={locale:Locale;setLocale:(v:Locale)=>void;name:string;setName:(v:string)=>void;sound:boolean;setSound:(v:boolean)=>void;streak:number;hearts:number;points:number;puzzleDone:boolean;completeLesson:()=>void;completePuzzle:()=>void;play:(tone?:"tap"|"win"|"wrong")=>void};
const C=createContext<AppState|undefined>(undefined);
export function AppProvider({children}:{children:ReactNode}){const[locale,setL]=useState<Locale>("en");const[name,setN]=useState("Sam");const[sound,setSoundState]=useState(true);const[streak,setStreak]=useState(7);const[hearts]=useState(5);const[points,setPoints]=useState(540);const[puzzleDone,setPuzzleDone]=useState(false);useEffect(()=>{const l=localStorage.getItem("ud_locale");if(l==="ar"||l==="en")setL(l);setN(localStorage.getItem("ud_name")||"Sam");setSoundState(localStorage.getItem("ud_sound")!=="off");setStreak(Number(localStorage.getItem("ud_streak")||7));setPoints(Number(localStorage.getItem("ud_points")||540));setPuzzleDone(localStorage.getItem("ud_puzzle_day")===new Date().toISOString().slice(0,10))},[]);const setLocale=(v:Locale)=>{setL(v);localStorage.setItem("ud_locale",v);document.documentElement.lang=v;document.documentElement.dir=v==="ar"?"rtl":"ltr"};const setName=(v:string)=>{setN(v);localStorage.setItem("ud_name",v)};const setSound=(v:boolean)=>{setSoundState(v);localStorage.setItem("ud_sound",v?"on":"off")};const play=(tone:"tap"|"win"|"wrong"="tap")=>{if(!sound||typeof window==="undefined")return;const AudioCtx=window.AudioContext||(window as typeof window & {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioCtx)return;const ctx=new AudioCtx();const notes=tone==="win"?[523,659,784]:tone==="wrong"?[220,175]:[440];notes.forEach((freq,n)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type="sine";o.frequency.value=freq;g.gain.setValueAtTime(.0001,ctx.currentTime+n*.08);g.gain.exponentialRampToValueAtTime(.09,ctx.currentTime+n*.08+.01);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+n*.08+.12);o.connect(g);g.connect(ctx.destination);o.start(ctx.currentTime+n*.08);o.stop(ctx.currentTime+n*.08+.14)});setTimeout(()=>ctx.close(),500)};const completeLesson=()=>{const today=new Date().toISOString().slice(0,10);if(localStorage.getItem("ud_lesson_day")!==today){localStorage.setItem("ud_lesson_day",today);setPoints(v=>{localStorage.setItem("ud_points",String(v+100));return v+100});setStreak(v=>{const next=v+1;localStorage.setItem("ud_streak",String(next));return next})}};const completePuzzle=()=>{localStorage.setItem("ud_puzzle_day",new Date().toISOString().slice(0,10));setPuzzleDone(true);setPoints(v=>{localStorage.setItem("ud_points",String(v+25));return v+25})};return <C.Provider value={{locale,setLocale,name,setName,sound,setSound,streak,hearts,points,puzzleDone,completeLesson,completePuzzle,play}}>{children}</C.Provider>}
export function useApp(){const c=useContext(C);if(!c)throw new Error("AppProvider missing");return c}
export function useCopy(){const{locale}=useApp();return locale==="ar"?ar:en}
export function Mascot({pose="wave",className}:{pose?:string;className?:string}){return <div className={cn("mascot",className)} role="img" aria-label={`Dojo ${pose}`}><div className="ear ear-a"/><div className="ear ear-b"/><div className="face"><span className="eye eye-a"/><span className="eye eye-b"/><span className="mask mask-a"/><span className="mask mask-b"/><span className="nose"/></div></div>}
export function Brand(){const t=useCopy();return <Link to="/home" className="flex items-center gap-2 font-display text-xl font-bold"><Mascot className="scale-75"/><span>{t.brand}</span></Link>}
export function Page({children,dark=false,nav=true}:{children:ReactNode;dark?:boolean;nav?:boolean}){const t=useCopy();return <div className={cn("min-h-dvh pb-24",dark&&"bg-primary text-primary-foreground")}><main className="mx-auto min-h-dvh w-full max-w-5xl px-5 py-5 sm:px-8">{children}</main>{nav&&<nav aria-label="Primary" className="fixed inset-x-0 bottom-0 z-30 mx-auto grid max-w-md grid-cols-4 border-t border-border bg-background/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur"><Nav to="/home" icon={<Home/>} label={t.home}/><Nav to="/topics" icon={<BookOpen/>} label={t.learn}/><Nav to="/society" icon={<Users/>} label={t.society}/><Nav to="/profile" icon={<UserRound/>} label={t.profile}/></nav>}</div>}
function Nav({to,icon,label}:{to:"/home"|"/topics"|"/society"|"/profile";icon:ReactNode;label:string}){return <Link to={to} activeProps={{className:"text-primary"}} className="flex min-h-14 flex-col items-center justify-center gap-1 text-[11px] text-muted-foreground [&_svg]:size-5">{icon}{label}</Link>}
export function Header({title,back}:{title?:string;back?:boolean}){const nav=useNavigate();const{locale,sound,setSound,play}=useApp();return <header className="mb-7 grid grid-cols-[auto_minmax(0,1fr)_auto_auto] items-center gap-2">{back?<Button variant="ghost" size="icon" className="min-h-11 min-w-11" aria-label="Back" onClick={()=>history.back()}>{locale==="ar"?<ArrowRight/>:<ArrowLeft/>}</Button>:<Brand/>}<div className="min-w-0">{title&&<h1 className="truncate font-display text-xl">{title}</h1>}</div><Button variant="ghost" size="icon" className="min-h-11 min-w-11" aria-label={sound?"Mute sounds":"Turn sounds on"} onClick={()=>{setSound(!sound);if(!sound)setTimeout(()=>play("tap"),0)}}>{sound?<Volume2/>:<VolumeX/>}</Button><Button variant="ghost" size="icon" className="min-h-11 min-w-11" aria-label="Settings" onClick={()=>nav({to:"/settings"})}><Settings/></Button></header>}
export function LanguageToggle(){const{locale,setLocale}=useApp();return <Button variant="outline" size="sm" className="min-h-11 rounded-full" onClick={()=>setLocale(locale==="en"?"ar":"en")}><Languages/>{locale==="en"?"العربية":"English"}</Button>}
export function TrackCard({track,index}:{track:(typeof tracks)[number];index:number}){const{locale}=useApp();return <Link to="/topics/$trackId" params={{trackId:track.id}} className="group block rounded-card border border-border bg-card p-5 shadow-soft transition-transform hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><div className="mb-8 flex items-start justify-between"><span className={cn("grid size-12 place-items-center rounded-button text-xl font-bold",index===1?"bg-accent text-accent-foreground":"bg-primary text-primary-foreground")}>{track.icon}</span><span className="text-sm text-muted-foreground">{track.lessons.length} {locale==="ar"?"دروس":"lessons"}</span></div><h3 className="font-display text-xl font-bold">{track.title[locale]}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{track.description[locale]}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-primary">{locale==="ar"?"استكشف المسار":"Explore track"}<ChevronRight className="directional size-4"/></span></Link>}
export function ProgressRing({value=3,total=5}:{value?:number;total?:number}){const p=value/total*100;return <div className="progress-ring" style={{"--progress":`${p*3.6}deg`} as React.CSSProperties}><div><strong>{value}</strong><span>/{total}</span></div></div>}
export function SectionTitle({eyebrow,title,action}:{eyebrow?:string;title:string;action?:ReactNode}){return <div className="mb-4 flex items-end justify-between gap-4"><div>{eyebrow&&<p className="mb-1 text-xs font-bold uppercase text-accent-foreground">{eyebrow}</p>}<h2 className="font-display text-2xl font-bold">{title}</h2></div>{action}</div>}
export function EmptyState({action}:{action?:ReactNode}){const t=useCopy();return <div className="py-14 text-center"><Mascot pose="reading" className="mx-auto mb-5 scale-125"/><p className="mx-auto max-w-xs text-muted-foreground">{t.empty}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export const icons={Check,LockKeyhole,MessageCircle,Share2,Sparkles};
