import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Award, Check, ChevronRight, Crown, Flame, Lightbulb, Share2, Trophy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Header, Mascot, Page, useApp } from "./app";
import { leaderboard } from "@/lib/unidojo-data";
import { cn } from "@/lib/utils";

export function PuzzlePage(){const{locale,puzzleDone,completePuzzle,play}=useApp();const[picks,setPicks]=useState<number[]>([]);const[done,setDone]=useState(puzzleDone);const amounts=[5,7,9,12];const total=picks.reduce((sum,i)=>sum+(amounts[i]??0),0);const target=21;function toggle(i:number){if(done)return;play();setPicks(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])}function check(){if(total===target){completePuzzle();setDone(true);play("win")}else play("wrong")}return <Page nav={false}><Header title={locale==="ar"?"لغز اليوم":"Daily puzzle"} back/><main className="mx-auto max-w-lg"><div className="reward-kicker"><Lightbulb/> {locale==="ar"?"دقيقتان فقط":"2 minute challenge"}</div><h1 className="mt-4 font-display text-4xl leading-tight">{locale==="ar"?"اصنع 21 جنيهاً":"Make exactly £21"}</h1><p className="mt-3 text-lg text-muted-foreground">{locale==="ar"?"اختر أقل عدد ممكن من الأظرف. يمكنك استخدام كل ظرف مرة واحدة.":"Choose the fewest envelopes you can. Each one can be used once."}</p><div className="my-9 grid grid-cols-2 gap-3">{amounts.map((n,i)=><button key={n} onClick={()=>toggle(i)} className={cn("money-tile",picks.includes(i)&&"selected")}>£{n}</button>)}</div><div className="rounded-card bg-primary p-5 text-primary-foreground"><div className="flex items-center justify-between"><span>{locale==="ar"?"المجموع":"Your total"}</span><strong className="font-display text-3xl">£{total}</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-primary-foreground/15"><div className="h-full bg-accent transition-all" style={{width:`${Math.min(100,total/target*100)}%`}}/></div></div>{done?<div className="celebration mt-5 rounded-card bg-success-soft p-5 text-center"><Mascot pose="success" className="mx-auto mb-4 scale-125"/><strong className="font-display text-2xl text-foreground">{locale==="ar"?"أحسنت! +25 نقطة":"Solved! +25 points"}</strong><Button asChild className="mt-5 w-full"><Link to="/home">{locale==="ar"?"العودة إلى المسار":"Back to my path"}</Link></Button></div>:<Button className="mt-5 min-h-12 w-full bg-accent text-accent-foreground" disabled={!picks.length} onClick={check}>{locale==="ar"?"تحقق":"Check my answer"}</Button>}</main></Page>}

export function LeaderboardPage(){const{locale,points}=useApp();return <Page><Header title={locale==="ar"?"لوحة المتصدرين":"Leaderboard"} back/><main className="mx-auto max-w-xl"><section className="rounded-card bg-primary p-6 text-primary-foreground"><div className="flex items-center gap-4"><div className="grid size-14 place-items-center rounded-full bg-accent text-accent-foreground"><Trophy/></div><div><p className="text-sm opacity-70">{locale==="ar"?"الدوري الأسبوعي":"Weekly league"}</p><h1 className="font-display text-3xl">{locale==="ar"?"دوري الحرم":"Campus League"}</h1></div></div><p className="mt-5 text-sm opacity-75">{locale==="ar"?"تعلّم بانتظام، وليس أكثر. يُعاد الترتيب كل اثنين.":"Consistency wins, not cramming. Rankings reset every Monday."}</p></section><ol className="mt-6 space-y-3">{leaderboard.map((x,i)=>{const score=x.me?points:x.score;return <li key={x.name} className={cn("grid grid-cols-[2rem_auto_1fr_auto] items-center gap-3 rounded-card border bg-card p-4",x.me&&"border-accent bg-accent-soft")}><strong>{i+1}</strong><span className="grid size-10 place-items-center rounded-full bg-primary font-bold text-primary-foreground">{x.avatar}</span><span><strong>{x.me?(locale==="ar"?"أنت":"You"):x.name}</strong>{x.me&&<small className="block text-muted-foreground">{locale==="ar"?"استمر!":"Keep going!"}</small>}</span><strong>{score}</strong></li>})}</ol></main></Page>}

export function CertificatePage(){const{locale,name}=useApp();return <Page nav={false}><Header title={locale==="ar"?"شهاداتك":"Your certificates"} back/><main className="mx-auto max-w-2xl"><section className="certificate-sheet text-center"><div className="certificate-seal"><Award/></div><p className="text-sm font-bold uppercase text-accent-foreground">UniDojo · Chapter One</p><h1 className="mt-5 font-display text-4xl">{locale==="ar"?"أساسيات المال":"Money Basics"}</h1><p className="mt-4 text-muted-foreground">{locale==="ar"?"تُمنح إلى":"Awarded to"}</p><p className="mt-2 font-display text-3xl">{name}</p><div className="mx-auto my-7 h-px max-w-xs bg-border"/><p className="mx-auto max-w-md leading-7 text-muted-foreground">{locale==="ar"?"لإكمال فصل شامل في التخطيط والإنفاق والادخار بثقة.":"For completing a comprehensive chapter in planning, spending and saving with confidence."}</p><div className="mt-8 flex items-center justify-center gap-2 text-success"><Check/><strong>{locale==="ar"?"متاح بعد إكمال 5 دروس":"Unlocks after 5 lessons"}</strong></div></section><Button variant="outline" className="mt-5 min-h-12 w-full" disabled><Share2/>{locale==="ar"?"مشاركة الشهادة":"Share certificate"}</Button></main></Page>}